using UnityEngine;
using UnityEngine.UI; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Yï¿½ê‚¸ï¿½É“ï¿½ï¿½ï¿½ï¿½

public class HpBarCtrl : MonoBehaviour
{
    [SerializeField, Header("Playerï¿½ï¿½hpï¿½ÌÅ‘ï¿½l")]
    public float _MaxHp = 0;
    [SerializeField, Header("ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½HPï¿½@ï¿½rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅÅ‘ï¿½lï¿½Éï¿½ï¿½í‚¹ï¿½ï¿½Ì‚Å•Kï¿½vï¿½È‚ï¿½")]
    public float _hp = 0;
    private Slider _slider;

    public bool Istalking = false;

    void Start()
    {
        // ï¿½Xï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
        _hp = _MaxHp;
    }
    void Update()
    {        // HPï¿½ã¸
        _hp += 0.01f;
        if (_hp > 1)

            if (Istalking == false)
            {

                _hp -= Time.deltaTime;
            }



        if (_hp < 0)
        {
            // ï¿½Å‘ï¿½ð’´‚ï¿½ï¿½ï¿½ï¿½ï¿½0ï¿½É–ß‚ï¿½
            _hp = 0;
        }

        // HPï¿½Qï¿½[ï¿½Wï¿½É’lï¿½ï¿½Ý’ï¿½
        _slider.value = _hp;
    }
    public void TalkEvent(float value)
    {
        _hp -= value;
    }
}